AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a custom VPC

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyApp-VPC

Outputs:
  VPCId:
    Value: !Ref VPC
