AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch log groups and metrics for ECS and Lambda

Resources:

  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/my-dotnet-app
      RetentionInDays: 14

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/MyAppEventProcessor
      RetentionInDays: 14

  RDSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /rds/myapp-db
      RetentionInDays: 14
