AWSTemplateFormatVersion: '2010-09-09'
Description: Store sensitive credentials in Secrets Manager

Parameters:
  AppName:
    Type: String
    Default: MyDotNetApp
  Environment:
    Type: String
    Default: dev
  DBUsername:
    Type: String
    Default: admin
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AppName}/${Environment}/DBCredentials"
      Description: RDS database credentials
      SecretString: !Sub |
        {
          "username": "${DBUsername}",
          "password": "${DBPassword}"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
