AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for .NET app image

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-dotnet-app
      ImageScanningConfiguration:
        scanOnPush: true
      Tags:
        - Key: Name
          Value: MyApp-ECR
