AWSTemplateFormatVersion: '2010-09-09'
Description: SQS queue subscribed to SNS topic

Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MyAppEventQueue

  SQSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSTopic
      Endpoint: !GetAtt SQSQueue.Arn
